Controllers/ExpenseCategoryController.cs
using ExpenseManagement.DataLayer;
using ExpenseManagement.Models;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseManagement.Controllers
{
    public class ExpenseCategoryController : Controller
    {
        public readonly DbContextExpMgt _context;

        public ExpenseCategoryController(DbContextExpMgt context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<ExpenseCategoryEntity> ExpenseCategories = _context.ExpenseCategory.ToList();
            return View(ExpenseCategories);
          
        }

        public IActionResult Create(ExpenseCategoryEntity expenseDetails)
        {
            if (ModelState.IsValid)
            {
                _context.ExpenseCategory.Add(expenseDetails);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            return View();
        }


        public IActionResult GetExpCatDetailsForUpdate(int? Id)
        {
            var _ExpenseCatDetails = _context.ExpenseCategory.Find(Id);
            if (_ExpenseCatDetails == null)
            {

                return NotFound();

            }
            return View(_ExpenseCatDetails);
        }

        [HttpPost]
        public IActionResult Update(ExpenseCategoryEntity _ExpenseCatDetails)
        {
            if (ModelState.IsValid)
            {
                _context.ExpenseCategory.Update(_ExpenseCatDetails);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            return View();

        }

        public IActionResult GetExpCatDetailsForDelete(int? Id)
        {
            var _ExpenseCatDetails = _context.ExpenseCategory.Find(Id);
            if (_ExpenseCatDetails == null)
            {

                return NotFound();

            }
            return View(_ExpenseCatDetails);
        }

        public IActionResult Delete(int? ExpenseCategoryId)
        {
            var _ExpenseCatDetails = _context.ExpenseCategory.Find(ExpenseCategoryId);
            if (_ExpenseCatDetails == null)
            {

                return NotFound();

            }
            _context.ExpenseCategory.Remove(_ExpenseCatDetails);
            _context.SaveChanges();
            return RedirectToAction("Index");


        }







    }
}

Controllers/ExpenseController.cs
using ExpenseManagement.DataLayer;
using ExpenseManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ExpenseManagement.Controllers
{
    public class ExpenseController : Controller
    {
        public readonly DbContextExpMgt _context;

        public ExpenseController(DbContextExpMgt context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<ExpenseEntity> expenseList = _context.Expenses.ToList();
            foreach (var obj in expenseList)
            {
                obj.ExpenseCategory = _context.ExpenseCategory.FirstOrDefault
                    (u=>u.ExpenseCategoryId==obj.ExpenseCategoryId);
            }
            return View(expenseList);
        }


        public IActionResult Create(ExpenseEntity expenseDetails)
        {
            IEnumerable<SelectListItem> getExpenseCategoryList =
                _context.ExpenseCategory.Select(i => new SelectListItem
                {
                    Text = i.ExpenseCategoryName,
                    Value = i.ExpenseCategoryId.ToString()

                });
            ViewBag.PopulateExpCategory = getExpenseCategoryList;

            if(ModelState.IsValid)
            {
                _context.Expenses.Add(expenseDetails);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            return View();
        }


        public IActionResult GetExpenseDetailsForUpdate(int? Id)
        {

            IEnumerable<SelectListItem> getExpenseCategoryList =
               _context.ExpenseCategory.Select(i => new SelectListItem
               {
                   Text = i.ExpenseCategoryName,
                   Value = i.ExpenseCategoryId.ToString()

               });
            ViewBag.PopulateExpCategory = getExpenseCategoryList;

            var _ExpenseDetails = _context.Expenses.Find(Id);
            if (_ExpenseDetails==null)
            {
              
                return NotFound();

            }
            return View(_ExpenseDetails);
        }

        [HttpPost]
        public IActionResult Update(ExpenseEntity expenseDetails)
        {
            if (ModelState.IsValid)
            {
                _context.Expenses.Update(expenseDetails);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            return View();

        }



        public IActionResult GetExpenseDetailsForDelete(int? Id)
        {
            IEnumerable<SelectListItem> getExpenseCategoryList =
              _context.ExpenseCategory.Select(i => new SelectListItem
              {
                  Text = i.ExpenseCategoryName,
                  Value = i.ExpenseCategoryId.ToString()

              });
            ViewBag.PopulateExpCategory = getExpenseCategoryList;


            var _ExpenseDetails = _context.Expenses.Find(Id);
            if (_ExpenseDetails == null)
            {

                return NotFound();

            }
            return View(_ExpenseDetails);
        }

        public IActionResult Delete(int? ExpenseId)
        {
            var _ExpenseDetails = _context.Expenses.Find(ExpenseId);
            if (_ExpenseDetails == null)
            {

                return NotFound();

            }
            _context.Expenses.Remove(_ExpenseDetails);
            _context.SaveChanges();
            return RedirectToAction("Index");


        }



    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpenseManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><h3>Expense Management</h3></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index"><b>My Expense</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExpenseCategory" asp-action="Index"><b> Expense category</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bottom:0;position:fixed;width:100%; background-color:orange; text-align:center;">
        <div class="container" style="bottom:0;position:fixed;width:140%; background-color:orange; text-align:center;">
            &copy; 2024 - Expense Management System  - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutUserProfile.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpenseManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-warning border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><h2>Expense Management</h2></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="bottom:0;position:fixed;width:100%; background-color:orange; text-align:center;">
        <div class="container" style="bottom:0;position:fixed;width:140%; background-color:orange; text-align:center;">
            &copy; 2024 - Expense Management System  - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>