Models/UserProfile.cs
using System.ComponentModel.DataAnnotations;

namespace ExpenseManagement.Models
{
    public class UserProfile
    {
        [Key]
        public int UserId { get; set; }




        [Required(ErrorMessage = "Please Enter Your First name")]
        [MinLength(3, ErrorMessage = "First name  is TOO SHORT")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }


        [Required(ErrorMessage = "Please Enter Your Last name")]
        [MinLength(3, ErrorMessage = "Last name is TOO SHORT")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Field can't be empty")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }

        [Required(ErrorMessage = "Please Enter Your Password")]
        public string Password { get; set; }
    }
}

Controllers/UserProfileController.cs
using ExpenseManagement.DataLayer;
using ExpenseManagement.Models;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseManagement.Controllers
{
    public class UserProfileController : Controller
    {
        private readonly DbContextExpMgt _context;

        public UserProfileController(DbContextExpMgt context)
        {
            _context = context; 
        }
        public IActionResult Login(string EmailAddress, string Password)
        {
            ViewBag.LoginStatus = "";
            if (ModelState.IsValid)
            {
                var userCheck = _context.UserProfile.FirstOrDefault
                    (a=>a.EmailAddress == EmailAddress && a.Password == Password);
                if (userCheck == null)
                {
                    ViewBag.LoginStatus = "Invalid Login or User not registered";
                }
                else
                {
                    return RedirectToAction("Index","Home");
                }
            }
            return View();
        }


        public IActionResult Registration(UserProfile userDetails)
        {
          
            if (ModelState.IsValid)
            {
               _context.UserProfile.Add(userDetails);
                _context.SaveChanges();
                return RedirectToAction("Login");
            }
            return View();
        }





        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/UserProfile/Login.cshtml
@model UserProfile

@{
    Layout = "_LayoutUserProfile";
    ViewData["title"] = "Login";
}

<form method="post" asp-action="Login">

        <div class="container align-content-center">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <p><b>@ViewBag.LoginStatus</b></p>   
        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="EmailAddress"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" type="password"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="w-12 btn-group" role="group">
            <input type="submit" class="btn btn-primary mx-1" value="Login" />
            <a asp-controller="UserProfile" asp-action="Registration" class="btn btn-success mx-1">Register</a>
        </div>


    </div>
</form>

Views/UserProfile/Registration.cshtml
@model UserProfile

@{
    Layout = "_LayoutUserProfile";
    ViewData["title"] = "Login";
}

<form method="post" asp-action="Registration">

        <div class="container align-content-center">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <p><b>@ViewBag.LoginStatus</b></p>   
        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
        </div>
        <br />


        <div class="row">
            <div class="col-4">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="EmailAddress"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="row">
            <div class="col-4">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" type="password"/>
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="w-12 btn-group" role="group">
            <input type="submit" class="btn btn-primary mx-1" value="Save" />
            <a asp-controller="UserProfile" asp-action="Login" class="btn btn-success mx-1">Cancel</a>
        </div>


    </div>
</form>